language: generic
sudo: required
dist: trusty

matrix:
  fast_finish: true

  include:
    - os: linux
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages:
            - g++-6
      env: CCOMPILER='gcc-6' CXXCOMPILER='g++-6'

    - os: linux
      addons:
        apt:
          sources: ['llvm-toolchain-trusty-3.9']
          packages:
            - clang-3.9
      env: CCOMPILER='clang-3.9' CXXCOMPILER='clang++-3.9'


before_install:
  - export CC=${CCOMPILER} CXX=${CXXCOMPILER}

script:
  - for source in *.cpp; do ${CXX} -Wall -Wextra -pedantic $source ; done

